2024-12-06 11:37:20,567 - ERROR - Error generating image: 'Images' object has no attribute 'create'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.images.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Images' object has no attribute 'create'
2024-12-06 11:37:20,568 - ERROR - Failed to generate image for wrestler test1
2024-12-06 11:37:20,569 - ERROR - Error generating image: 'Images' object has no attribute 'create'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.images.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Images' object has no attribute 'create'
2024-12-06 11:37:20,570 - ERROR - Failed to generate image for wrestler test
2024-12-06 11:37:20,570 - ERROR - Error generating image: 'Images' object has no attribute 'create'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.images.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Images' object has no attribute 'create'
2024-12-06 11:37:20,570 - ERROR - Failed to generate image for wrestler test
2024-12-06 11:37:20,571 - ERROR - Error generating image: 'Images' object has no attribute 'create'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.images.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Images' object has no attribute 'create'
2024-12-06 11:37:20,571 - ERROR - Failed to generate image for wrestler test1
2024-12-06 13:56:37,512 - ERROR - Error generating image: 'OpenAI' object has no attribute 'Image'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.Image.create(
               ^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'Image'. Did you mean: 'images'?
2024-12-06 13:56:37,513 - ERROR - Failed to generate image for wrestler test1
2024-12-06 13:56:37,515 - ERROR - Error generating image: 'OpenAI' object has no attribute 'Image'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.Image.create(
               ^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'Image'. Did you mean: 'images'?
2024-12-06 13:56:37,516 - ERROR - Failed to generate image for wrestler test
2024-12-06 13:56:37,516 - ERROR - Error generating image: 'OpenAI' object has no attribute 'Image'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.Image.create(
               ^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'Image'. Did you mean: 'images'?
2024-12-06 13:56:37,517 - ERROR - Failed to generate image for wrestler test
2024-12-06 13:56:37,517 - ERROR - Error generating image: 'OpenAI' object has no attribute 'Image'
Traceback (most recent call last):
  File "D:\1.) Creative\Coding Solutions\Wrestleverse Generation\wrestleverse.py", line 446, in generate_image
    response = self.client.Image.create(
               ^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAI' object has no attribute 'Image'. Did you mean: 'images'?
2024-12-06 13:56:37,518 - ERROR - Failed to generate image for wrestler test1
